### ISSUE TITLE
 Property 'generateServiceProviderMetadata' does not exist on type 'Strategy'

### ISSUE THREAD

**Issue by thsenthilkumar** [jaredhanson/passport-strategy#14]
I have upgraded "@node-saml/passport-saml":"4.0.4" to the latest version

then started getting this error 

TypeScript error: error TS2339: Property 'generateServiceProviderMetadata' does not exist on type 'Strategy'.

**Comment by jaredhanson** [comment]
That sounds like an issue with that package, not this one. Closing.
